name: Exercice 01 - Fundamentals

on:
  workflow_dispatch:
  pull_request:

jobs:
  exercise-01-fundamentals-info:
    uses: exercices/exercise-01-fundamentals/reusable-example.yml
    with:
      node-version: "20"
