name: Exercice 01 - Fundamentals

on:
  workflow_dispatch:
  pull_request:

jobs:
  exercise-01-fundamentals-info:
    uses: ./exercices/exercice-01-fundamentals/.github/workflows/reusable-example.yml@v1
    with:
      node-version: "20"
