name: Build and Test API
on: 
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{steps.changes.outputs.api}}
    steps:
      - name: Check changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            api:
              - 'components/api/**'

  build-api:
   runs-on: ubuntu-latest
   timeout-minutes: 15
   defaults:
    run:
      working-directory: components/api
   steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: cache deps
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: components/api/package-lock.json
    - name: install deps
      run: npm ci
    - name: build api
      run: npm run build

  test-api:
    needs: [check-changes, build-api]
    if: needs.check-changes.outputs.api == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: components/api
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: install deps
        run: npm ci
      - name: run tests
        run: npm run test:coverage

