name: Deploy API production

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  API-build:
    name: Build API component
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        working-directory: components/api

    steps:
      - name: checkout the repo
        uses: actions/checkout@v4

      - name: Use Node 20 / cache dependencies
        uses: actions/setup-node
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: components/api/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build API
        run: npm run build

  Api-deploy:
    name: Deploy API docker image to GHCR
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [API-build]

    steps:
      - name: checkout the repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: setup docker buildX
        uses: docker/setup-buildx-action@v3

      - name: build and push API docker Image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: components/api
          file: components/api/Dockerfile
          push: true
          tags: ghcr.io/${{github.repository}}/api
          cache-from: type=gha
          cache-to: type=gha,mode=max
