name: Deploy API production

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  API-build:
    uses: ./.github/workflows/reusable-api-ci.yml
    permissions:
      pull-requests: write
      contents: read

  Api-deploy:
    name: Deploy API docker image to GHCR
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [API-build]

    steps:
      - name: checkout the repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: setup docker buildX
        uses: docker/setup-buildx-action@v3

      - name: build and push API docker Image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: components/api
          file: components/api/Dockerfile
          push: true
          tags: ghcr.io/${{github.repository}}/api
          cache-from: type=gha
          cache-to: type=gha,mode=max
