name: lint, build Web component

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: false
        default: "20"
      package-manager:
        type: string
        required: false
        default: "npm"
      cache-dependency-path:
        type: string
        required: true

permissions:
  contents: read

jobs:
  build-Web:
    name: lint and build the web component
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: components/web

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: use node version 20 / cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.NODE_VERSION}}
          cache: ${{inputs.package-manager}}
          cache-dependency-path: ${{inputs.cache-dependency-path}}

      - name: Install dependencies
        run: npm ci

      - name: lint web
        run: npm run lint

      - name: Build Web
        run: npm run build
