name: lint, build Web component

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-Web:
    name: lint and build the web component
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: components/core

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: use node version 20 / cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: ${{env.PACKAGE_MANAGER}}
          cache-dependency-path: ${{github.workspace}}/components/web

      - name: Install dependencies
        run: npm ci

      - name: lint web
        run: npm run lint

      - name: Build Web
        run: npm run build
